#!/usr/bin/env python
#

# for the framework
from sys             import argv
from getopt          import getopt, GetoptError

# for the pattern generation
from tmtpl.utils     import stdo
from tmtpl.std_app   import StdApp
from tmtpl.pattern   import *

# Project specific
from math import sin, cos, radians

from pysvg.filter import *
from pysvg.gradient import *
from pysvg.linking import *
from pysvg.script import *
from pysvg.shape import *
from pysvg.structure import *
from pysvg.style import *
from pysvg.text import *
from pysvg.builders import *

# CmdlineError
#
# The type of exception that will be raised by Cmdline.process() if there
# are command line processing errors.
#
class CmdlineError(Exception):
    # __init__
    #
    def __init__(self, error):
        self.msg = error

# Cmdline
#
# Do all the command line processing.
#
class Cmdline:
    # __init__
    #
    def __init__(self):
        self.cfg = {}

    # error
    #
    def error(self, e, defaults):
        if e != '': print e
        self.usage(defaults)

    # usage
    #
    # Prints out the help text which explains the command line options.
    #
    def usage(self, defaults):
        stdo("    Usage:                                                                                   \n")
        stdo("        %s [--verbose] [--config=<cfg file>] --client=<client file> [--debug=[dump]] outfile \n" % self.cfg['app_name'])
        stdo("                                                                                             \n")
        stdo("    Options:                                                                                 \n")
        stdo("        --help           Prints this text.                                                   \n")
        stdo("                                                                                             \n")
        stdo("        --verbose        Give some feedback of what is happening while the script is         \n")
        stdo("                         running.                                                            \n")
        stdo("                                                                                             \n")
        stdo("        --config=<cfg file>                                                                  \n")
        stdo("                         The full path to the configuration file to use instead of           \n")
        stdo("                         the default location.                                               \n")
        stdo("                                                                                             \n")
        stdo("        --client=<client file>                                                               \n")
        stdo("                         The full path to the client data file to use.                       \n")
        stdo("                                                                                             \n")
        stdo("        --debug=[dump]                                                                       \n")
        stdo("                         Performs additional output related to the option enabled and        \n")
        stdo("                         the application defined support for the option.                     \n")
        stdo("                                                                                             \n")
        stdo("    Examples:                                                                                \n")
        stdo("        %s --verbose out.svg                                                                 \n" % self.cfg['app_name'])

    # process
    #
    # As you can probably tell from the name, this method is responsible
    # for calling the getopt function to process the command line. All
    # parameters are processed into class variables for use by other
    # methods.
    #
    def process(self, argv, defaults):
        self.cfg['app_name'] = argv[0]
        result = True
        try:
            optsShort = ''
            optsLong  = ['help', 'verbose', 'config=', 'client=', 'debug=']
            opts, args = getopt(argv[1:], optsShort, optsLong)

            if len(args) != 1:
                raise CmdlineError('You must supply an output file name\n\n')
                
            self.cfg['args'] = args

            for opt, val in opts:
                if (opt == '--help'):
                    raise CmdlineError('')

                elif (opt == '--verbose'):
                    self.cfg['verbose'] = True

                elif opt in ('--config'):
                    self.cfg['configuration_file'] = val

                elif opt in ('--client'):
                    self.cfg['client_file'] = val

                elif opt in ('--debug'):
                    self.cfg['debug'] = val.split(',')

        except GetoptError, error:
            print(error, defaults)
            raise CmdlineError('')

        return self.cfg

    # verify_options
    #
    def verify_options(self, cfg):
        # can add code here as needed
        return


# AppTemplate
#
class AppTemplate(StdApp):
    # __init__
    #
    def __init__(self):
        StdApp.__init__(self)
        self.defaults = {}

    # main
    #
    def main(self):
        cmdline = Cmdline()
        try:
            self.merge_config_options(self.defaults, cmdline.process(argv, self.defaults))
            cmdline.verify_options(self.cfg)

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        # Handle command line errors.
        #
        except CmdlineError as e:
            cmdline.error(e.msg, self.defaults)
            return

        if self.cfg.has_key('verbose'):
            verbose = True
        else:
            verbose = False

        if self.cfg.has_key('client_file'):
            mfn = self.cfg['client_file']
            if verbose:
                print "Using client file: ", mfn
        else:
            cmdline.error('Error: You must specify a client file\n\n', self.defaults)
            return

        dbgdump = False
        if self.cfg.has_key('debug'):
            debug = self.cfg['debug']
            if "dump" in debug:
                dbgdump = True
                print "Debug: dump enabled"
        else:
            dbgdump = False

        # open the client file and read the data
        client = Client(self.cfg['client_file'])
        cd = client.data

        if dbgdump:
            print "========== Client Data Dump =========="
            print client.dump(),
            print "======== End Client Data Dump ========"

        # TODO - abstract these into configuration file(s)
        # pattern name
        company_name  = 'New Day'
        pattern_name     = 'Steampunk Jacket'
        pattern_number  = '1870-M-J-1'
        pattern_pieces    = 7

        # create the document info and fill it in
        docinfo = docInfo()
        docinfo.clientdata = cd
        docinfo.company_name = company_name
        docinfo.pattern_name = pattern_name
        docinfo.pattern_number = pattern_number

        # TODO also extract these from this file to somewhere else
        printer='36" wide carriage plotter'
        if (printer == '36" wide carriage plotter'):
            docinfo.paper_width  = ( 36 * in_to_pt )
            docinfo.border       = ( 1 * in_to_pt )        # 1" document borders

        #
        # Begin the real work here
        #
        # svg constants
        svgNameText = []
        no_transform = ''   # no transform required

        # create the svg document itself
        sz = svg("TMTP test")

        # add the scripting we need to handle events
        # TODO for now don't
        #sc = script()
        #sc.set_xlink_href("mouse_over.js")
        #sc.set_xlink_type("text/ecmascript")
        #sz.addElement(sc)
        #sz.set_onload("init(evt)")

        # Add attributes
        #
        sz.set_width('auto')
        sz.set_height('auto')
        sz.setAttribute('currentScale', "0.05 : 1")
        sz.setAttribute('fitBoxtoViewport', "True")
        sz.setAttribute('preserveAspectRatio', "xMidYMid meet")
        sz.setAttribute('margin-bottom', str(docinfo.border))
        sz.setAttribute('margin-left', str(docinfo.border))
        sz.setAttribute('margin-right', str(docinfo.border))
        sz.setAttribute('margin-top', str(docinfo.border))
        sz.setAttribute('company-name', docinfo.company_name)
        sz.setAttribute('patttern-number', docinfo.pattern_number)
        sz.setAttribute('pattern-name', docinfo.pattern_name)
        sz.setAttribute('client-name', cd.customername)

        # Add namespaces
        #
        # TODO - note sure if any of these are required
        #sz.setAttribute('xmlns:cc', "http://creativecommons.org/ns#")
        # dc xmlns:dc="http://purl.org/dc/elements/1.1/"
        # u'rdf'      :u'http://www.w3.org/1999/02/22-rdf-syntax-ns#',
        # u'sodipodi' :u'http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd',
        # u'inkscape' :u'http://www.inkscape.org/namespaces/inkscape',
        # u'xml'      :u'http://www.w3.org/XML/1998/namespace',
        # u'xpath'    :u'http://www.w3.org/TR/xpath',
        # u'xsl'      :u'http://www.w3.org/1999/XSL/Transform'

        # reference & pattern layers - implemented as groups
        reference_group = g() # reference_layer = reference information
        reference_group.set_id('Reference')
        pattern_group = g()  # pattern_layer = pattern lines & marks
        reference_group.set_id('Pattern')

        # draw the title block
        docinfo.drawTitleBlock(pattern_group)

        # Add the groups
        sz.addElement(reference_group)
        sz.addElement(pattern_group)
        # Write out the svg file
        sz.save(self.cfg['args'][0])
        return

        oh = ShapeBuilder()

        # use an incrementing counter to set element IDs
        idcount = 0

        # draw 24 hour markers like a clock face
        for hour in range (0, 24):
            ang = (hour + tz) * 15
            tx, ty = polar2Rect(timelength, ang-90)
            sz.addElement(oh.createLine(xoff, yoff, xoff + tx, yoff + ty, strokewidth=2, stroke="lightgray"))

            tx, ty = polar2Rect(timetextlen, ang-90)
            dh = hour - 6
            if dh < 0:
                dh = dh + 24
            tt = str(dh)
            t = text(tt, tx + xoff, ty + yoff)
            sz.addElement(t)

        # Draw the text element for use with mouse events
        t = text("text box", xoff, 20)
        t.set_id("textNode")
        sz.addElement(t)

        # Draw the QSO points
        recs = adifParse(self.cfg['args'][0])
        for rec in recs:
            
            if (dumprecords):
                print rec

            call = rec["call"]
            if not rec.has_key('gridsquare'):
                if (verbose):
                    print "skipping (no grid) " + call
                continue

            if isUSCall(call):
                if (verbose):
                    print "skipping (US) " + call
                continue

            angle = angleFromTime(rec["time_on"]) + (tz * 15)
            distance, azimuth = bearingDistance(rec["my_gridsquare"], rec["gridsquare"])
            distance = distance / scale

            bx, by = polar2Rect(distance, angle-90)
            fillcolor = freq2Color(rec["freq"])

            eid = str(idcount)
            idcount = idcount + 1

            #poptext = rec["call"] + " " + str(rec["freq"])
            dot = circle(bx + xoff, by + yoff, dotsize)
            # appearance
            dot.set_fill(fillcolor)
            dot.set_stroke('black')
            # attributes and such
            dot.set_id(eid)
            dot.setAttribute("call", call)
            dot.setAttribute("freq", rec['freq'])
            dot.setAttribute("time", rec['time_on'])
            dot.setAttribute("date", rec['qso_date'])

            # events
            #dot.set_onmouseover('showQSO(evt)')
            #dot.set_onmouseout('hideQSO(evt)')
            #dot.set_onclick('QSOClick("' + rec["call"] + '")')

            sz.addElement(dot)

        sz.save("./testout.svg")


        return

if __name__ == '__main__':
    app = AppTemplate()
    app.main()

# vi:set ts=4 sw=4 expandtab:

