#!/usr/bin/env python
#

# for the framework
from sys             import argv
from getopt          import getopt, GetoptError

# for the pattern generation
from tmtpl.utils     import stdo
from tmtpl.std_app   import StdApp

from tmtpl.constants import *
from tmtpl.pattern   import *
from tmtpl.document   import *
from tmtpl.support   import *
from tmtpl.client   import Client

# Project specific
#from math import sin, cos, radians

from pysvg.filter import *
from pysvg.gradient import *
from pysvg.linking import *
from pysvg.script import *
from pysvg.shape import *
from pysvg.structure import *
from pysvg.style import *
from pysvg.text import *
from pysvg.builders import *

# CmdlineError
#
# The type of exception that will be raised by Cmdline.process() if there
# are command line processing errors.
#
class CmdlineError(Exception):
    # __init__
    #
    def __init__(self, error):
        self.msg = error

# Cmdline
#
# Do all the command line processing.
#
class Cmdline:
    # __init__
    #
    def __init__(self):
        self.cfg = {}

    # error
    #
    def error(self, e, defaults):
        if e != '': print e
        self.usage(defaults)

    # usage
    #
    # Prints out the help text which explains the command line options.
    #
    def usage(self, defaults):
        stdo("    Usage:                                                                                   \n")
        stdo("        %s [--verbose] [--config=<cfg file>] --client=<client file> [--debug=[dump]] outfile \n" % self.cfg['app_name'])
        stdo("                                                                                             \n")
        stdo("    Options:                                                                                 \n")
        stdo("        --help           Prints this text.                                                   \n")
        stdo("                                                                                             \n")
        stdo("        --verbose        Give some feedback of what is happening while the script is         \n")
        stdo("                         running.                                                            \n")
        stdo("                                                                                             \n")
        stdo("        --config=<cfg file>                                                                  \n")
        stdo("                         The full path to the configuration file to use instead of           \n")
        stdo("                         the default location.                                               \n")
        stdo("                                                                                             \n")
        stdo("        --client=<client file>                                                               \n")
        stdo("                         The full path to the client data file to use.                       \n")
        stdo("                                                                                             \n")
        stdo("        --debug=[dump]                                                                       \n")
        stdo("                         Performs additional output related to the option enabled and        \n")
        stdo("                         the application defined support for the option.                     \n")
        stdo("                                                                                             \n")
        stdo("    Examples:                                                                                \n")
        stdo("        %s --verbose out.svg                                                                 \n" % self.cfg['app_name'])

    # process
    #
    # As you can probably tell from the name, this method is responsible
    # for calling the getopt function to process the command line. All
    # parameters are processed into class variables for use by other
    # methods.
    #
    def process(self, argv, defaults):
        self.cfg['app_name'] = argv[0]
        result = True
        try:
            optsShort = ''
            optsLong  = ['help', 'verbose', 'config=', 'client=', 'debug=']
            opts, args = getopt(argv[1:], optsShort, optsLong)

            if len(args) != 1:
                raise CmdlineError('You must supply an output file name\n\n')
                
            self.cfg['args'] = args

            for opt, val in opts:
                if (opt == '--help'):
                    raise CmdlineError('')

                elif (opt == '--verbose'):
                    self.cfg['verbose'] = True

                elif opt in ('--config'):
                    self.cfg['configuration_file'] = val

                elif opt in ('--client'):
                    self.cfg['client_file'] = val

                elif opt in ('--debug'):
                    self.cfg['debug'] = val.split(',')

        except GetoptError, error:
            print(error, defaults)
            raise CmdlineError('')

        return self.cfg

    # verify_options
    #
    def verify_options(self, cfg):
        # can add code here as needed
        return


# AppTemplate
#
class AppTemplate(StdApp):
    # __init__
    #
    def __init__(self):
        StdApp.__init__(self)
        self.defaults = {}

    # main
    #
    def main(self):
        cmdline = Cmdline()
        try:
            self.merge_config_options(self.defaults, cmdline.process(argv, self.defaults))
            cmdline.verify_options(self.cfg)

        # Handle the user presses <ctrl-C>.
        #
        except KeyboardInterrupt:
            pass

        # Handle command line errors.
        #
        except CmdlineError as e:
            cmdline.error(e.msg, self.defaults)
            return

        if self.cfg.has_key('verbose'):
            verbose = True
        else:
            verbose = False

        if self.cfg.has_key('client_file'):
            mfn = self.cfg['client_file']
            if verbose:
                print "Using client file: ", mfn
        else:
            cmdline.error('Error: You must specify a client file\n\n', self.defaults)
            return

        dbgdump = False
        if self.cfg.has_key('debug'):
            debug = self.cfg['debug']
            if "dump" in debug:
                dbgdump = True
                print "Debug: dump enabled"
        else:
            dbgdump = False

        # open the client file and read the data
        client = Client(self.cfg['client_file'])
        cd = client.data

        if dbgdump:
            print "========== Client Data Dump =========="
            print client.dump(),
            print "======== End Client Data Dump ========"

        # pattern name
        pattern_pieces    = 7

        # TODO also extract these from this file to somewhere else
        printer='36" wide carriage plotter'
        if (printer == '36" wide carriage plotter'):
            paper_width  = ( 36 * in_to_pt )
            border       = ( 1 * in_to_pt )        # 1" document borders


        # create the document info and fill it in
        # TODO - abstract these into configuration file(s)
        companyName = 'New Day'
        patternName = 'Steampunk Jacket'
        patternNumber = '1870-M-J-1'
        clientName = cd.customername

        # attributes for the entire svg document
        docattrs = {'currentScale' : "0.05 : 1",
                    'fitBoxtoViewport' : "True",
                    'preserveAspectRatio' : "xMidYMid meet",
                    'margin-bottom' : str(border),
                    'margin-left' : str(border),
                    'margin-right' : str(border),
                    'margin-top' : str(border),
                    'company-name' : companyName,
                    'pattern-number' : patternNumber,
                    'pattern-name' : patternName,
                    'client-name' : clientName
                    }

        doc = Document(self.cfg['args'][0], name = 'document', attributes = docattrs)

        # TODO also extract these from this file to somewhere else
        printer='36" wide carriage plotter'
        if (printer == '36" wide carriage plotter'):
            doc.paper_width  = paper_width
            doc.border       = border

        # Set up the title block
        tb = TitleBlock('pattern', 'titleblock', doc.border, doc.border,
                        company_name = companyName, pattern_name = patternName,
                        pattern_number = patternNumber, client_name = clientName,
                        stylename = 'titleblock_text_style')
        doc.add(tb)

        #
        # Begin the real work here
        #
        # svg constants TODO I think I removed the need for these
        #svgNameText = []
        #no_transform = ''   # no transform required



        # pattern start, count & placement
        x = border
        y = border

        begin = Point('reference', 'begin', x,   (y + PATTERN_OFFSET), 'point_style')
        doc.add(begin)

        # This was here, and used later to calculate doc size
        # TODO may not be needed
        #layout = Layout( 'layout',  begin.x,  begin.y,  reference_layer)

        # may not be needed??
        #docinfo.lowx = begin.x
        #docinfo.lowy = begin.y

        # The whole pattern in a jacket
        jacket = Pattern('jacket')
        doc.add(jacket)

        # Set up styles dictionary
        # for now just hardcode these here
        # TODO - load then from a file
        jacket.styledefs['point_style'] = { 
            'stroke' : 'red',
            'fill' : 'red',
            'stroke-width' : '1'
            }
        jacket.styledefs['reference_path_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4',
                'stroke-dasharray'   : '6,18',
            'stroke-dashoffset'  : '0'
            }
        jacket.styledefs['default'] = {
            'fill'               : 'none',
            'stroke'             : 'red',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4',
            }
        jacket.styledefs['line_path_style'] = {
            'fill'               : 'none',
            'stroke'             : 'pink',
            'stroke-width'       : '5',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['dart_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '5',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['foldline_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '2',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['hemline_path_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '2',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['seamline_path_style'] = {
            'fill'               : 'none',
            'stroke'             : 'green',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4',
            'stroke-dasharray'   : '24,6',
            'stroke-dashoffset'  : '0'
            }
        jacket.styledefs['cuttingline_style'] = {
            'fill'               : 'none',
            'stroke'             : 'green',
            'stroke-width'       : '6',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['placement_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4',
            'stroke-dasharray'   : '6,18',
            'stroke-dashoffset'  : '0'
            }
        jacket.styledefs['grainline_style'] = {
            'fill'               : 'none',
            'stroke'             : 'green',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['buttonhole_style'] = {
            'fill'               : 'none',
            'stroke'             : 'gray',
            'stroke-width'       : '4',
            'stroke-linejoin'    : 'miter',
            'stroke-miterlimit'  : '4'
            }
        jacket.styledefs['tooltip_text_style'] = {
            'vertical-align':'top',
            'fill-opacity':'1.0',
            'font-size':'50',
            'font-style':'normal',
            'fill':'blue',
            'font-weight':'normal',
            'stroke':'black',
            'text-anchor':'right',
            'text-align':'right'
            }
        jacket.styledefs['titleblock_text_style'] = {
            'vertical-align':'top',
            'fill-opacity':'1.0',
            'font-size':'40',
            'font-style':'normal',
            'fill':'#000000',
            'font-weight':'normal',
            'stroke':'none',
            'text-anchor':'right',
            'text-align':'right'
            }
        jacket.styledefs['point_text_style'] = {
            'vertical-align':'top',
            'fill-opacity':'1.0',
            'font-size':'15',
            'font-style':'normal',
            'fill':'#000000',
            'font-weight':'normal',
            'stroke':'none',
            'text-anchor':'right',
            'text-align':'right'
            }

        # TEMP Save it
        sf = open('tmtp_styles.json', 'w+')
        sf.write(json.dumps(jacket.styledefs, sort_keys=True, indent=4))
        sf.close()

        # Create the back pattern piece
        back = PatternPiece('pattern', 'back', letter = 'A', fabric = 2, interfacing = 0, lining = 0)
        jacket.add(back)

        jb = jacket.back

        start =  Point('reference', 'start', begin.x, begin.y, 'point_style')
        jb.add(start)

        jb.attrs['transform'] = 'translate(' + jb.start.coords + ' )'
        jb.add(Point('reference', 'low', 0, 0, 'point_style'))
        jb.add(Point('reference', 'high', 0, 0, 'point_style'))

        jb.width = max(cd.back.shoulder.width, cd.back.chest.width, cd.back.waist.width, cd.back.hip.width) \
            + (2*SEAM_ALLOWANCE) + (3*cm_to_pt)  # 3cm ease assumed
        jb.height = cd.back.neck.length + cd.back.jacket.length + HEM_ALLOWANCE + (2*SEAM_ALLOWANCE) + (3*cm_to_pt) #3cm ease assumed

        nape = Point('reference', 'nape', 0, 0, 'point_style')
        jb.add(nape)

        # reference back center seam points for nape, shoulder, chest, waist, hip, hem
        jb.add(Node('seam'))
        jb.seam.add(Node('center'))
        jb.seam.center.add(Point('reference', 'shoulder', jb.nape.x, jb.nape.y + cd.back.shoulder.length, 'point_style'))
        jb.seam.center.add(Point('reference', 'chest', jb.nape.x + (1*cm_to_pt), jb.nape.y + cd.back.chest.length, 'point_style'))
        jb.seam.center.add(Point('reference', 'waist', jb.nape.x + (2.5*cm_to_pt), jb.nape.y + cd.back.waist.length, 'point_style'))
        jb.seam.center.add(Point('reference', 'hip', jb.nape.x + (2*cm_to_pt), jb.seam.center.waist.y + cd.back.hip.length, 'point_style'))
        jb.seam.center.add(Point('reference', 'hem', jb.nape.x + (1.5*cm_to_pt), cd.back.jacket.length, 'point_style'))
        jb.seam.center.add(Point('reference', 'hem_allowance', jb.seam.center.hem.x +0, jb.seam.center.hem.y + HEM_ALLOWANCE, 'point_style'))

        # reference back side seam points for chest, waist, hip, hem
        jb.seam.add(Node('side'))
        jb.seam.side.add(Point('reference', 'chest', jb.nape.x + cd.back.shoulder.width - (1*cm_to_pt),  jb.nape.y + cd.back.chest.length, 'point_style'))
        jb.seam.side.add(Point('reference', 'waist', jb.nape.x + cd.back.shoulder.width - (3*cm_to_pt),  jb.nape.y + cd.back.waist.length, 'point_style'))
        jb.seam.side.add(Point('reference', 'hip', jb.nape.x + cd.back.shoulder.width - (2*cm_to_pt),  jb.seam.side.waist.y + cd.back.hip.length, 'point_style'))
        jb.seam.side.add(Point('reference', 'hem', jb.nape.x + cd.back.shoulder.width - (1.5*cm_to_pt),   cd.back.jacket.length, 'point_style'))
        jb.seam.side.add(Point('reference', 'hem_allowance', jb.seam.side.hem.x, jb.seam.side.hem.y + HEM_ALLOWANCE, 'point_style'))

        # armscye points
        jb.add(Point('reference', 'balance', jb.nape.x + cd.back.shoulder.width,  jb.nape.y + cd.back.balance.length, 'point_style'))
        jb.add(Point('reference', 'underarm', jb.nape.x + cd.back.shoulder.width,
                     jb.nape.y + cd.back.balance.length + abs(cd.back.balance.length - cd.back.chest.length)*(.48), 'point_style'))

        # diagonal shoulder line
        jb.seam.add(Node('shoulder'))
        jb.seam.shoulder.add(Point('reference', 'high', jb.nape.x + cd.back.neck.width, jb.nape.y - cd.back.neck.length, 'point_style'))
        jb.seam.shoulder.add(Point('reference', 'low', jb.seam.center.shoulder.x + cd.back.shoulder.width + (1*cm_to_pt), jb.seam.center.shoulder.y, 'point_style'))

        # Back Vertical Reference Grid
        bgrid = Node('grid')
        jb.add(bgrid)
        bgrid.add(Line('reference', 'center', 'Jacket Back - Center', nape.x, nape.y, nape.x, nape.y +jb.height, 'reference_path_style')) # vertical line
        bgrid.add(Line('reference', 'shoulderwidth', 'Jacket Back - Shoulder Width', nape.x + cd.back.shoulder.width,
                       nape.y, nape.x + cd.back.shoulder.width, nape.y + jb.height, 'reference_path_style'))
        bgrid.add(Line('reference', 'side', 'Jacket Back - Side', nape.x + jb.width, nape.y, nape.x + jb.width, nape.y + jb.height, 'reference_path_style'))
        jbss = jb.seam.shoulder
        bgrid.add(Line('reference', 'neck', 'Jacket Back - Neck', jbss.high.x, jbss.high.y, jbss.high.x, jbss.high.y + cd.back.neck.length, 'reference_path_style'))

        # Back Horizontal Reference Grid
        bgrid.add(Line('reference', 'top', 'Jacket Back - Top', nape.x, nape.y, nape.x + jb.width, nape.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'shoulder', 'Jacket Back - Shoulder', nape.x, jb.seam.center.shoulder.y, nape.x + jb.width, jb.seam.center.shoulder.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'chest', 'Jacket Back - Chest', nape.x, jb.seam.center.chest.y, nape.x + jb.width, jb.seam.center.chest.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'waist', 'Jacket Back - Waist', nape.x, jb.seam.center.waist.y, nape.x + jb.width, jb.seam.center.waist.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'hip', 'Jacket Back - Hip', nape.x, jb.seam.center.hip.y, nape.x + jb.width, jb.seam.center.hip.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'hem', 'Jacket Back - Hem', nape.x, jb.seam.center.hem.y, nape.x + jb.width, jb.seam.center.hem.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'hem_allowance', 'Jacket Back - Hem Allowance', nape.x, jb.seam.center.hem_allowance.y,
                       nape.x + jb.width, jb.seam.center.hem_allowance.y, 'reference_path_style'))
        bgrid.add(Line('reference', 'end', 'Jacket Back - End', nape.x, jb.nape.y + jb.height, nape.x + jb.width,  jb.nape.y + jb.height, 'reference_path_style'))

        # Back Center Seam line clockwise from bottom left:

        # Control Points
        distance = abs(jb.seam.center.hip.y - jb.seam.center.waist.y )*(.3)
        x, y = pointAlongLine(jb.seam.center.hip.x, jb.seam.center.hip.y, jb.seam.center.hem.x, jb.seam.center.hem.y, - distance)
        jb.add(Point('reference', 'c1', x, y, 'point_style'))
        jb.add(Point('reference', 'c2', jb.seam.center.waist.x, jb.seam.center.waist.y + abs(jb.seam.center.waist.y - jb.seam.center.hip.y) * (.3), 'point_style'))
        jb.add(Point('reference', 'c3', jb.seam.center.waist.x, jb.seam.center.waist.y - abs(jb.seam.center.waist.y - jb.seam.center.chest.y) * (.3), 'point_style'))

        distance = abs( jb.seam.center.chest.y - jb.seam.center.waist.y )*(.3)
        x, y = pointAlongLine(jb.seam.center.chest.x, jb.seam.center.chest.y, jb.seam.center.shoulder.x, jb.seam.center.shoulder.y, - distance)
        jb.add(Point('reference', 'c4', x, y, 'point_style'))

        jb.add(Point('reference', 'c5', jb.seam.center.chest.x - abs(jb.seam.center.chest.x - jb.seam.center.shoulder.x)*(.3),
                     jb.seam.center.chest.y - abs( jb.seam.center.chest.y - jb.seam.center.shoulder.y )*(.3), 'point_style'))
        jb.add(Point('reference', 'c6', jb.seam.center.shoulder.x, jb.seam.center.shoulder.y + abs( jb.seam.center.shoulder.y - jb.seam.center.chest.y )*(.3), 'point_style'))

        # Back Neck seam line clockwise from jb.nape to high point of shoulder:
        distance = (abs( jb.seam.shoulder.high.y - jb.nape.y )*(.75))
        x, y = pointAlongLine(jb.seam.shoulder.high.x, jb.seam.shoulder.high.y, jb.seam.shoulder.low.x, jb.seam.shoulder.low.y, distance, 90)
        #jb.add(Line('reference', 'debug2', 'Debug2', jb.nape.x, jb.nape.y, jb.seam.shoulder.high.x, jb.nape.y)) # DEBUG
        jb.add(Point('reference', 'c7', x, y, 'point_style')) # perpendicular to shoulder line at jb.seam.shoulder.high.

        distance = (abs( jb.seam.shoulder.high.x - jb.nape.x ) ) * (.50)
        x, y = pointAlongLine(jb.nape.x, jb.nape.y, jb.seam.shoulder.high.x, jb.nape.y, distance)
        jb.add(Point('reference', 'c8', x, y, 'point_style'))

        # Back Shoulder & Armhole seam lines clockwise from high point to low point of shoulder to top of side seam
        jb.add(Point('reference', 'c9',
                     jb.seam.shoulder.high.x + (abs( jb.seam.shoulder.low.x - jb.seam.shoulder.high.x )*(.33)),
                     jb.seam.shoulder.high.y + (abs( jb.seam.shoulder.low.y - jb.seam.shoulder.high.y )*(.4)), 'point_style'))

        jb.add(Point('reference', 'c10',
                     jb.seam.shoulder.high.x + (abs( jb.seam.shoulder.low.x - jb.seam.shoulder.high.x )*(.6) ),
                     jb.seam.shoulder.high.y + (abs( jb.seam.shoulder.low.y - jb.seam.shoulder.high.y )*(.66)), 'point_style'))


        # Back Side seam line clockwise from jb.underarm. to hem
        distance = abs(jb.seam.center.chest.y - jb.seam.side.waist.y) * (.3)
        x, y = pointAlongLine(jb.seam.side.chest.x, jb.seam.side.chest.y, jb.underarm.x, jb.underarm.y, - distance)
        jb.add(Point('reference', 'c11', x, y, 'point_style'))

        jb.add(Point('reference', 'c12', jb.seam.side.waist.x, jb.seam.side.waist.y - (abs( jb.seam.side.waist.y - jb.seam.side.chest.y )*(.3)), 'point_style'))
        jb.add(Point('reference', 'c13', jb.seam.side.waist.x, jb.seam.side.waist.y + (abs( jb.seam.side.waist.y - jb.seam.side.hip.y )*(.3)), 'point_style'))

        distance = (abs(jb.seam.side.waist.y - jb.seam.side.hip.y)*(.3))
        x, y = pointAlongLine(jb.seam.side.hip.x, jb.seam.side.hip.y, jb.seam.side.hem.x, jb.seam.side.hem.y, - distance)
        jb.add(Point('reference', 'c14', x, y, 'point_style'))

        # Grainline
        # TODO Put this in a Grainline class that includes arrows, styling, etc
        jb.add(Point('reference', 'g1', (jb.seam.shoulder.low.x)/2, jb.underarm.y, 'point_style'))
        jb.add(Point('reference', 'g2', jb.g1.x, jb.g1.y + (25*cm_to_pt), 'point_style'))
        jb.add(Line('reference', 'grainline', 'Grainline', jb.g1.x, jb.g1.y, jb.g2.x, jb.g2.y, 'grainline_style'))
        # End Grainline


        # Assemble all paths down here
        # Paths are a bit differemt - we create the SVG and then create the object to hold it
        # See the pysvg library docs for the pysvg methods
        path_svg = path()
        jb.add(Path('pattern', 'path', 'Jacket Back Path', path_svg, 'seamline_path_style'))

        # Back Neck Seam path - starts with 'jacket.back.nape' from Back_Center_Seam
        # Was jb.seam.neck.path = 'M ' + jb.nape.coords + ' C '+ c8.coords +' '+ c7.coords +' '+ jb.seam.shoulder.high.coords
        path_svg.appendMoveToPath(jb.nape.x, jb.nape.y, relative = False)
        path_svg.appendCubicCurveToPath(jb.c8.x, jb.c8.y, jb.c7.x, jb.c7.y, jb.seam.shoulder.high.x, jb.seam.shoulder.high.y, relative = False)

        # Back Shoulder Seam path - starts with 'jacket.back.seam.shoulder.high.coords' from Back_Neck_Seam
        # Was jb.seam.shoulder.path = ' C '+ c9.coords +' '+ c10.coords +' '+ jb.seam.shoulder.low.coords
        path_svg.appendCubicCurveToPath(jb.c9.x, jb.c9.y, jb.c10.x, jb.c10.y, jb.seam.shoulder.low.x, jb.seam.shoulder.low.y, relative = False)

        # Was jb.seam.armhole.path  = ' Q ' + jb.balance.coords + ' ' + jb.underarm.coords
        #jb.add(Line('reference', 'debug1', 'Debug1', jb.balance.x, jb.balance.y, jb.underarm.x, jb.underarm.y)) # DEBUG
        path_svg.appendQuadraticCurveToPath(jb.balance.x, jb.balance.y, jb.underarm.x, jb.underarm.y, relative = False)

        # Back Side Seam path -- starts with 'jacket.back.underarm.' from Back_Shoulder_Armhole_Seam
        # Was jb.seam.side.path  = ' L '+ jb.seam.side.chest.coords +' C '+ c11.coords + ' '+ c12.coords +' '+ jb.seam.side.waist.coords +
        # ' C '+ c13.coords +' '+ c14.coords +' '+ jb.seam.side.hip.coords +' L '+ jb.seam.side.hem.coords + ' ' + jb.seam.side.hem_allowance.coords
        path_svg.appendLineToPath(jb.seam.side.chest.x, jb.seam.side.chest.y, relative = False)
        path_svg.appendCubicCurveToPath(jb.c11.x, jb.c11.y, jb.c12.x, jb.c12.y, jb.seam.side.waist.x, jb.seam.side.waist.y, relative = False)
        path_svg.appendCubicCurveToPath(jb.c13.x, jb.c13.y, jb.c14.x, jb.c14.y, jb.seam.side.hip.x, jb.seam.side.hip.y, relative = False)
        path_svg.appendLineToPath(jb.seam.side.hem.x, jb.seam.side.hem.y, relative = False)
        path_svg.appendLineToPath(jb.seam.side.hem_allowance.x, jb.seam.side.hem_allowance.y, relative = False) # not sure of this, no operator in original

        # Back Center Seam path
        # Was jb.seam.center.path  = 'L '+ jb.seam.center.hem_allowance.coords + ' L '+  jb.seam.center.hem.coords + ' L ' +  jb.seam.center.hip.coords +
        # ' C '+ c1.coords +' '+ c2.coords +' '+ jb.seam.center.waist.coords + ' C '+ c3.coords +' '+ c4.coords +' '+ jb.seam.center.chest.coords +
        # ' C '+ c5.coords +' '+ c6.coords + ' '+ jb.seam.center.shoulder.coords + ' L '+ jb.nape.coords

        path_svg.appendLineToPath(jb.seam.center.hem_allowance.x, jb.seam.center.hem_allowance.y, relative = False)
        path_svg.appendLineToPath(jb.seam.center.hem.x, jb.seam.center.hem.y, relative = False)
        path_svg.appendLineToPath(jb.seam.center.hip.x, jb.seam.center.hip.y, relative = False)
        path_svg.appendCubicCurveToPath(jb.c1.x, jb.c1.y, jb.c2.x, jb.c2.y, jb.seam.center.waist.x, jb.seam.center.waist.y, relative = False)
        path_svg.appendCubicCurveToPath(jb.c3.x, jb.c3.y, jb.c4.x, jb.c4.y, jb.seam.center.chest.x, jb.seam.center.chest.y , relative = False)
        path_svg.appendCubicCurveToPath(jb.c5.x, jb.c5.y, jb.c6.x, jb.c6.y, jb.seam.center.shoulder.x, jb.seam.center.shoulder.y, relative = False)
        path_svg.appendLineToPath(jb.nape.x, jb.nape.y, relative = False)
        path_svg.appendCloseCurve()

        # Back Hemline path
        # Was jb.seam.hem.path = 'M ' +  jb.seam.center.hem.coords + ' L ' + jb.seam.side.hem.coords
        path_hemline = path()
        jb.add(Path('pattern', 'hemline', 'Jacket Back Hemline', path_hemline, 'hemline_path_style'))
        path_hemline.appendMoveToPath(jb.seam.center.hem.x, jb.seam.center.hem.y, relative = False)
        path_hemline.appendLineToPath(jb.seam.side.hem.x, jb.seam.side.hem.y, relative = False)
        
        #
        # Temporary End
        #

        # TODO make this dynamic when we have bounding box calculations
        doc.height = 24 * in_to_pt
        doc.width = 14 * in_to_pt
        doc.draw()
        return

        jb.seam.add(Node('neck'))
        jb.seam.add(Node('armhole'))
        jb.seam.add(Node('hem'))


        #
        # Temporary End
        #
        doc.draw()
        return

if __name__ == '__main__':
    app = AppTemplate()
    app.main()

# vi:set ts=4 sw=4 expandtab:

